services:
  teamspeak:
    image: teamspeak:latest
    container_name: teamspeak-server
    restart: unless-stopped
    ports:
      - 9987:9987/udp
      - 10011:10011
      - 30033:30033
    environment:
      TS3SERVER_DB_PLUGIN: ts3db_mariadb
      TS3SERVER_DB_SQLCREATEPATH: create_mariadb
      TS3SERVER_DB_HOST: teamspeak-db
      TS3SERVER_DB_USER: root
      TS3SERVER_DB_PASSWORD: ${TEAMSPEAK_DB_PASSWORD}
      TS3SERVER_DB_NAME: teamspeak
      TS3SERVER_DB_WAITUNTILREADY: 30
      TS3SERVER_LICENSE: accept
    volumes:
      - ./data:/var/ts3server/

  teamspeak-db:
    image: mariadb:11.2.6
    container_name: teamspeak-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${TEAMSPEAK_DB_PASSWORD}
      MYSQL_DATABASE: teamspeak
    volumes:
      - ./sql:/var/lib/mysql/
